apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/geloasacode/k8s-fleetman.git
    targetRevision: HEAD
    path: main-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated: 
      selfHeal: true
      prune: true
